# Generated by Django 2.2a1 on 2020-06-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getImage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
